version: '3'
services:
  app:
    build: api
    ports:
      - "8000:8000"
    volumes:
      - ./api/db/:/api/db
    links:
      - twitch

  twitch:
    build: twitch
    ports:
      - "49152:49152"
    volumes:
      - ./api/db/:/twitch/db